//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamento1
    {
        public int codigo { get; set; }
        public string descricao { get; set; }
        public string tipo { get; set; }
    }
}
