//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preco
    {
        public int validade { get; set; }
        public decimal valor { get; set; }
        public int idEquipamento { get; set; }
        public bool hidden { get; set; }
    
        public virtual Equipamento Equipamento { get; set; }
    }
}
